package ar.edu.um.entidad;

// Generated Feb 2, 2014 7:21:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMensaje generated by hbm2java
 */
@Entity
@Table(name = "tipoMensaje", catalog = "canario")
public class TipoMensaje implements java.io.Serializable {

	private int idTipoMensaje;
	private String nombre;	

	public TipoMensaje() {
	}

	public TipoMensaje(int idTipoMensaje, String nombre) {
		this.idTipoMensaje = idTipoMensaje;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "idTipoMensaje", unique = true, nullable = false)
	public int getIdTipoMensaje() {
		return this.idTipoMensaje;
	}

	public void setIdTipoMensaje(int idTipoMensaje) {
		this.idTipoMensaje = idTipoMensaje;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
